### ISSUE TITLE
Couldn't connect to server

### ISSUE THREAD

**Issue by hexandwhy** [sparkychild/ChuChuBoTTT#11]
I keep getting this message:

---

| Welcome to Pokemon Showdown Bot! |
| --- |

ok      starting server
Warning: Native modules not compiled.  XOR performance will be degraded.
Warning: Native modules not compiled.  UTF-8 validation disabled.
info    Rooms are not loaded.
ok      Loaded command files: ambush.js
ok      Loaded command files: anagrams.js
ok      Loaded command files: battle.js
ok      Loaded command files: blackjack.js
ok      Loaded command files: bot.js
ok      Loaded command files: crazyeights.js
ok      Loaded command files: customcommands.js
ok      Loaded command files: dev.js
ok      Loaded command files: economy.js
ok      Loaded command files: flexibility.js
ok      Loaded command files: game.js
ok      Loaded command files: general.js
ok      Loaded command files: hangman.js
ok      Loaded command files: kunc.js
ok      Loaded command files: misc.js
ok      Loaded command files: mod.js
ok      Loaded command files: passthebomb.js
ok      Loaded command files: resetcommands.js
ok      Loaded command files: roleplaying.js
ok      Loaded command files: statspread.js
ok      Loaded command files: trivia.js
ok      Loaded command files: wifi.js
info    connecting to ws://sim.smogon.com:8000/showdown/892/02_91hc1/websocket - secondary protocols: [ 3 ]
error   Could not connect to server sim.smogon.com: 'Expected a Sec-WebSocket-Protocol header.'

What am I doing wrong?

**Comment by sparkychild** [comment]
i think main PS server may have changed to sim.psim.us

**Comment by hexandwhy** [comment]
info    connecting to ws://sim.psim.us:8000/showdown/659/b9fbn9ys/websocket - secondary protocols: [ 3 ]
error   Could not connect to server sim.psim.us: 'Expected a Sec-WebSocket-Protocol header.'

I got this message instead...

Edit: btw, using

exports.override = {
    server: "sim.psim.us",
    port: 8000,
    serverid: "showdown"
}

on config.js
